name: RPG-Items
version: ${project.version}-b${BUILD_NUMBER}
description: >
  Create custom items in the style of games like Torchlight.

authors: [thinkofdeath, TfT_02]
main: think.rpgitems.RPGItems
website: http://dev.bukkit.org/server-mods/rpg-items/
softdepend: [WorldGuard]

commands:
    rpgitem:
        description: RPG Items
        usage: 